#!/bin/bash
read -p "Enter prod-e or prod-f : " n1
filter="$n1"
AWS_INSTANCE_WITH_ID=$(aws ec2 describe-instances --filter Name=tag:stack,Values="${filter}"  --query "Reservations[*].Instances[*].[InstanceId]" --output text)


for instance_id in $AWS_INSTANCE_WITH_ID
            do
                        echo $instance_id
                            # Now get CPU against instance ID from cloud metrics one by one against that tag for past 2 hours
                                aws cloudwatch get-metric-statistics --metric-name CPUUtilization --start-time 2020-12-10T17:18:00 --end-time 2020-12-10T19:18:00Z --period 3600 --namespace AWS/EC2 --statistics Maximum --dimensions Name=InstanceId,Value=$instance_id --output table
